### PR TITLE
Thêm toàn bộ file

### PR DESCRIPTION
**Pull request by hpn00689**

### CODE REVIEW

**Comment by David-Sat** [comment]
You're welcome to make a fork of this project, but please make sure that you are not committing your API key to the repository.

**Comment by hpn00689** [comment]
Dear David,

I'm very sorry for my carelessness, I cloned your application repository
directly instead of your forked repository.  This app is great for my
younger siblings to practice critical thinking, thanks for your idea.



Vào 1:21, CN, 17 thg 3, 2024 David Satomi ***@***.***> đã
viết:

**Comment by David-Sat** [comment]
Thanks for the great feedback! It also shouldn't be hard to switch the model provider if needed. How did you find this repository?

**Comment by hpn00689** [comment]
My NLP course instructor introduced me to the lab.ai homepage and its
excellent applications. As a personal interest, I enjoy following debates,
so I searched for similar applications and discovered Ai ThinkTank. I
intend to use this application for personal purposes (teaching my younger
siblings) and to enhance its features for my end-of-term report to my
instructor. Currently, the features I am considering include updating chat
history, reading PDFs, summarizing arguments, as well as generating English
vocabulary to assist users in learning foreign languages through debates.

Vào 2:01, CN, 17 thg 3, 2024 David Satomi ***@***.***> đã
viết:

**Comment by David-Sat** [comment]
Sound very cool! Good luck with your course :)

**Pull request closed without merging**
